name: fastapi-demo

services:
  # 应用服务配置
  fastapi-demo:
    image: fastapi-demo
    container_name: fastapi-demo  # 容器名称
    platform: linux/amd64 # 构建后到服务端使用
    build:
      context: .  # 使用当前目录作为构建上下文
      dockerfile: Dockerfile
    restart: unless-stopped # 自动重启
    ports:
      - "10024:10024"  # 映射应用端口
    environment:
      # 使用宿主机的网络，可以通过 host.docker.internal 访问宿主机的服务
      - DB_HOST=host.docker.internal 
    extra_hosts:
      - "host.docker.internal:host-gateway"

